<Project>

    <Import Project="$(MSBuildThisFileDirectory)LocalCS.props" />

    <PropertyGroup>
        <LocalCS Condition="!$(MSBuildProjectName.EndsWith('Generators'))">$(LocalCSOverride)</LocalCS>
        <LocalCS Condition="$(MSBuildProjectName.EndsWith('Generators'))">false</LocalCS>
        <UnderlingsProjectPath Condition="'$(UnderlingsProjectPath)' == ''">$(MSBuildThisFileDirectory)Underlings/Underlings/Underlings.csproj</UnderlingsProjectPath>
        <UnderlingsGeneratorsProjectPath Condition="'$(UnderlingsGeneratorsProjectPath)' == ''">$(MSBuildThisFileDirectory)Underlings/Underlings.Generators/Underlings.Generators.csproj</UnderlingsGeneratorsProjectPath>
        <ClientStructsRoot Condition="'$(Configuration)' != 'Private'">$(MSBuildThisFileDirectory)..\..\FFXIVClientStructs</ClientStructsRoot>
        <ClientStructsRoot Condition="'$(Configuration)' == 'Private'">$(MSBuildThisFileDirectory)..\..\FFXIVClientStructs-RE</ClientStructsRoot>
    </PropertyGroup>

    <Import Project="$(MSBuildThisFileDirectory)Directory.Build.props.user"
            Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.props.user')" />

    <ItemGroup Condition="'$(LocalCS)'=='true'">
        <ProjectReference Include="$(ClientStructsRoot)\FFXIVClientStructs\FFXIVClientStructs.csproj" Private="true" />
        <ProjectReference Include="$(ClientStructsRoot)\InteropGenerator.Runtime\InteropGenerator.Runtime.csproj" Private="true" />
    </ItemGroup>

    <ItemGroup Condition="'$(LocalCS)'=='true'">
        <ProjectReference Include="$(ClientStructsRoot)\InteropGenerator\InteropGenerator.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <PropertyGroup Condition="'$(LocalCS)'=='true'">
        <DefineConstants>$(DefineConstants);LOCAL_CS</DefineConstants>
        <Use_Dalamud_FFXIVClientStructs>false</Use_Dalamud_FFXIVClientStructs>
    </PropertyGroup>

</Project>
